#!/bin/bash

BUILD_DIR=build

if [ ! -d "$DIRECTORY" ];
then
    mkdir -p ./build/ ; cd ./build/ ; cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ ; cd ..
fi
if [ $# == 0 ] || [ $1 == "all" ]
then
    make -C $BUILD_DIR -j
elif [ $# != 1 ]
then
    echo "Usage: $0 [rule]"
elif [ $1 == "setup" ]
then
    rm -rf ./build/ ; mkdir -p ./build/ ; cd ./build/ ; cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ ; cd ..
elif [ $1 == "installscript" ]
then
    sudo cp cbuild /usr/bin/
else
    make $1 -C $BUILD_DIR -j
fi
